# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dbdb6111316a924a3f80c14eb103db138761bf00dcf93c8087f9f2f022aeaee5f638ca0b0dda76dfe42e886d790df684c99c680fe15caa00a6396dbc7f96bbb

test:
  secret_key_base: afccaad75f88fc1cd2a433f261571a15508f196c65eb7393baf0ecae35a25d3532bbe4d0d50b00fbb956712bd186f809c393208a3086b50ba35ba10d3d6408b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
